# Generated by Django 3.1.1 on 2020-10-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('composer', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=100)),
                ('multipart', models.BooleanField()),
            ],
        ),
    ]
