# Generated by Django 3.1.2 on 2020-10-07 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('venue', models.CharField(choices=[('STJ', 'at St. John'), ('OPC', 'at Oglethorpe Presbyterian Church'), ('RIN', 'as a Paid Ringer'), ('FUN', 'at a Funeral'), ('WED', 'at a Wedding')], default='STJ', max_length=3)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.song')),
            ],
        ),
    ]
