# Generated by Django 3.1.2 on 2020-10-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('publihser', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='performance',
            name='date',
            field=models.DateField(verbose_name='performance date'),
        ),
    ]
