# Generated by Django 3.1.2 on 2020-10-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_song_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publihser',
            new_name='publisher',
        ),
    ]
